name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ../../devops_essentials/docker-alpine-extended/Dockerfile --file Dockerfile --tag my-docker-image:$(date +%s)
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push Docker image to registry
      run: docker push ghcr.io/${{ github.repository_owner }}/my-docker-image:latest
